# Site settings
title: LHDV.net
email: lh@lhdv.net
description: > # this means to ignore newlines until "baseurl:"
  Just some thoughts about anything. As a developer and human being.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lhdv.net" # the base hostname & protocol for your site
twitter_username: 
github_username:  lhdv

# Build settings
markdown: kramdown

# timezone: America/Sao_Paulo

production_url : http://lhdv.net
gems:
- jekyll-sitemap
